site_name: OSG Management Area
site_url: https://opensciencegrid.github.io/management
repo_url: https://github.com/opensciencegrid/management
theme: readthedocs

extra_css:
  - css/extra.css

pages:
  - Home: 'index.md'
  - Area Coordinators: 'area-coordinators.md'
  - AC Meeting Archive: 'ac-meeting-archive.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
