site_name: OSG Management Area
site_url: https://opensciencegrid.github.io/management/
repo_url: null
theme:
  name: material
  custom_dir: osgthedocs
  favicon: img/favicon.ico

pages:
  - Home: 'index.md'
  - Area Coordinators: 'area-coordinators.md'
  - AC Meeting Archive: 'ac-meeting-archive.md'
  - Policies: 'policies.md'

markdown_extensions:
  - admonition
  - toc(permalink=true)
